#!/usr/bin/env bash

# get version of currently installed PepperFlashPlayer
version=$(cat /Library/Internet\ Plug-Ins/PepperFlashPlayer/manifest.json | /usr/local/bin/jq ".version")
# remove quotes so the version argument is passed to open without them
version=$(echo $version | tr -d '"')

# NOTE: display version for debugging
# echo $version
# osascript -e "tell application \"SystemUIServer\"
# display dialog \"$version\"
# end"

# start binary as daemon without nohup.out file or any other output
# echo "nohup /Applications/Chromium.app/Contents/MacOS/Chromium --ppapi-flash-path=/Library/Internet\ Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin/ --ppapi-flash-version=$version"
nohup /Applications/Chromium.app/Contents/MacOS/Chromium --ppapi-flash-path=/Library/Internet\ Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin/ --ppapi-flash-version=$version &>/dev/null &
